### PR TITLE
Add options for GCR auth

### PR DESCRIPTION
**Pull request by dekkagaijin**
Add references to installing `docker-credential-{gcr, gcloud}`

### CODE REVIEW

**Comment by viglesiasce** [comment]
Thanks @dekkagaijin!! Should we just be recommending the `gcloud auth configure-docker`? It seems like that one is the best option. Any gotchas?

**Comment by dekkagaijin** [comment]
> Should we just be recommending the gcloud auth configure-docker? It seems like that one is the best option.

I'd guess that that should work for 99% of users doing local development and pushing to GCR, but  `docker-credential-gcr` exists for those that don't want to take a dependency on `gcloud` (and python).

> Any gotchas?

It's currently in beta, pending GA release for Docker 18.03 (or whichever version thereafter ends up being stable). Fixed the command to reflect that.

**Comment by viglesiasce** [comment]
Awesome. Maybe once that goes GA we can remove the other two and refer out to the GCP docs for "other options".

**Comment by dekkagaijin** [comment]
sgtm, I'll swing around when it lands

**Pull request merged**
