### PR TITLE
docs: split verbose config template from getting-started example

### LINKED ISSUE #107: Separate example config YAML from the reference template
Right now the example's skaffold.yaml https://github.com/GoogleCloudPlatform/skaffold/blob/f321400fb678007d85a1df88f6dc8a0a9ed63f60/examples/getting-started/skaffold.yaml is the file that has the most documentation.

Consider creating a `skaffold.yaml.template` with that documentation, and reducing the example yaml to only the stuff that's uncommented.

This way:
- you can have 1 source of truth for documentation (rather than replicating it in each example)
- have brief examples that just work without requiring user to read every single field's description (less steep learning curve).

### PR DESCRIPTION
**Pull request by r2d4**
fixes #107

### CODE REVIEW

**Comment by dlorenc** [comment]
This makes sense, but where is the .tmpl used or linked from?

**Comment by r2d4** [comment]
Nowhere, its just a nice verbose config for reference. Maybe it should be .yaml so that gets syntax highlighted

**Comment by dlorenc** [comment]
> Nowhere, its just a nice verbose config for reference. Maybe it should be .yaml so that gets syntax highlighted

Yeah, if we're not actually using it as a template I'd keep it as yaml.

**Comment by r2d4** [comment]
done ptal @dlorenc

**Pull request merged**
